FROM node:latest

# Set the working directory within the container
WORKDIR /app

# Copy the Next.js client code into the container
COPY . .

# Install dependencies
# RUN npm install

# Build the Next.js client for production
# RUN npm run build

# Expose the port that the Next.js client will listen on (if needed)
EXPOSE 3003

# Define the command to start the Next.js client in production mode
# CMD ["npm", "start"]
CMD ["sh", "-c", "npm install && npm start"]