import Navbar from "@/components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";
import Hero from "@/components/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "MUSE",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    "bg-white h-screen w-screen flex flex-col items-start overflow-x-hidden"
                )}
            >
                <Navbar />
                <main className="flex-grow container">
                    <Hero/>
                </main>
                {children}
                <Footer />
            </body>
        </html>
    );
}
