import Navbar from "@/components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, " bg-gradient-to-b from-sky-100 to-blue-300 px-6 md:px-10 lg:px-[7%] xl:px-[10%] 2xl:px-[17%] h-screen w-screen justify-center items-start")}>
        <Navbar />
        <main>{children}</main>
        
      </body>
    </html>
  );
}
