# Use the official Go image as the base image
FROM golang:latest

# Set the working directory within the container
WORKDIR /app

# Copy the Go server code into the container
COPY . .

# Build the Go server
# RUN go build -o main .

# Expose the port that the server will listen on
EXPOSE 3005

# Define the command to start the Go server
CMD ["go", "run", "main.go"]
