package util

const (
	EN_INTERNAL_SERVER_ERROR       = "EN_INTERNAL_SERVER_ERROR"
	EN_API_PARAMETER_INVALID_ERROR = "EN_API_PARAMETER_INVALID_ERROR"
	EN_UNAUTHENTICATED_ERROR       = "EN_UNAUTHENTICATED_ERROR"
	EN_UNAUTHORIZED_ERROR          = "EN_UNAUTHORIZED_ERROR"
	EN_INVALID_TOKEN_ERROR         = "EN_INVALID_TOKEN_ERROR"
	EN_SOMETHING_WRONG             = "EN_SOMETHING_WRONG"
	EN_NOT_FOUND                   = "EN_NOT_FOUND"
	EN_ALREADY_REGISTERED_ERROR    = "EN_ALREADY_REGISTERED_ERROR"
)
